// frontend/src/components/section/NavbarComponent.tsx
import React, { useMemo } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { useNotification } from '../../context/NotificationContext';
import NotificationComponent from '../notification/NotificationComponent';

const NavbarComponent: React.FC = () => {
  const { user, logout: authLogout } = useAuth();
  const { show } = useNotification();
  const navigate = useNavigate();

  const avatarUrl = useMemo(() => 
    `https://api.dicebear.com/9.x/bottts/svg?seed=${user?.first_name || 'user'}`,
    [user?.first_name]
  );

  const handleLogout = () => {
    authLogout();
    localStorage.removeItem('justLoggedIn');
    show('You have successfully logged out', 'error');
    navigate('/');
  };

  return (
    <nav className="bg-white shadow-sm border-b border-gray-200 relative z-50 font-['Inter']">
      <NotificationComponent />

      <div className="flex items-center justify-between px-6 py-4 w-full">
        <div className="flex items-center gap-2">
          <Link to="/" className="text-2xl font-extrabold text-black">
            Reservelt
          </Link>
        </div>

        <div className="flex items-center gap-6">
          {!user ? (
            <>
              <Link
                to="/for-restaurants"
                className="text-sm font-semibold text-gray-700 hover:text-gray-900"
              >
                For restaurants
              </Link>

              <Link
                to="/login"
                className="text-sm font-semibold text-gray-700 hover:text-gray-900"
              >
                Log In
              </Link>

              <Link
                to="/signup"
                className="text-sm font-semibold bg-black text-white px-5 py-2 rounded-md hover:bg-gray-800 transition duration-200"
              >
                Sign Up
              </Link>
            </>
          ) : (
            <>
              <Link to="/profile">
                <img
                  src={avatarUrl}
                  alt="Avatar"
                  className="w-10 h-10 rounded-full border border-gray-300 hover:ring-2 ring-gray-300 transition"
                />
              </Link>

              <button
                onClick={handleLogout}
                className="text-sm font-semibold text-gray-700 hover:text-red-600 transition duration-200"
              >
                Log Out
              </button>
            </>
          )}
        </div>
      </div>
    </nav>
  );
};

export default NavbarComponent;

// frontend/src/components/Navbar/NavbarComponent.vue
<template>
  <nav class="bg-white shadow-md border-b-2 border-gray-300">
    <div class="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
      <div class="flex items-center gap-2">
        <h1 class="text-3xl font-extrabold text-black">Reservelt</h1>
      </div>

      <div class="hidden md:flex gap-10 items-center text-black font-semibold">
        <a href="#" class="hover:text-blue-700 transition duration-200">Discover</a>
        <a href="#" class="hover:text-blue-700 transition duration-200">Events</a>
        <a href="#" class="hover:text-blue-700 transition duration-200">Pricing</a>
        <a href="#" class="hover:text-blue-700 transition duration-200">Contact</a>
      </div>

      <div class="hidden md:flex items-center gap-6">
        <router-link
          to="/login"
          class="text-md font-semibold text-black hover:text-gray-600 transition duration-200"
        >
          Login
        </router-link>

        <router-link
          to="/signup"
          class="text-md font-semibold bg-black text-white px-6 py-2 rounded-full hover:bg-gray-800 transition duration-200 shadow-lg"
        >
          Sign Up
        </router-link>
      </div>

      <button
        class="md:hidden inline-flex items-center justify-center rounded-md p-2 text-black hover:text-gray-600 hover:bg-gray-100 transition duration-200"
      >
        <svg xmlns="http://www.w3.org/2000/svg" class="h-7 w-7" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
      </button>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'NavbarComponent',
};
</script>
